export enum Permissions {
  // USER
  CREATE_UPDATE_USER = "CREATE_UPDATE_USER",
  CHANGE_ROLE = "CHANGE_ROLE",
  GET_USER = "GET_USER",

  // PERMISSION
  GET_PERMISSION = "GET_PERMISSION",
  GET_PERMISSION_MODULE = "GET_PERMISSION_MODULE",
  CREATE_UPDATE_ROLE = "CREATE_UPDATE_ROLE",
  GET_ROLE = "GET_ROLE",
  DELETE_ROLE = "DELETE_ROLE",

  // CLASS
  CREATE_UPDATE_CLASS = "CREATE_UPDATE_CLASS",
  DELETE_CLASS = "DELETE_CLASS",
  GET_CLASS = "GET_CLASS",

  // CLASS
  CREATE_UPDATE_SUBJECT = "CREATE_UPDATE_SUBJECT",
  DELETE_SUBJECT = "DELETE_SUBJECT",
  GET_SUBJECT = "GET_SUBJECT",

  // CHAPTER
  CREATE_UPDATE_CHAPTER = "CREATE_UPDATE_CHAPTER",
  DELETE_CHAPTER = "DELETE_CHAPTER",
  GET_CHAPTER = "GET_CHAPTER",

  // EXAM TYPE
  CREATE_UPDATE_EXAM_TYPE = "CREATE_UPDATE_EXAM_TYPE",
  DELETE_EXAM_TYPE = "DELETE_EXAM_TYPE",
  GET_EXAM_TYPE = "GET_EXAM_TYPE",

  // EXAM CATEGORY
  CREATE_UPDATE_EXAM_CATEGORY = "CREATE_UPDATE_EXAM_CATEGORY",
  DELETE_EXAM_CATEGORY = "DELETE_EXAM_CATEGORY",
  GET_EXAM_CATEGORY = "GET_EXAM_CATEGORY",

  // EXAM
  CREATE_UPDATE_EXAM = "CREATE_UPDATE_EXAM",
  DELETE_EXAM = "DELETE_EXAM",
  GET_EXAM = "GET_EXAM",
}
